export const questions = [
  {
    id: "0",
    number: "1",
    title: "次の暗号を解読してね",
    question:
      "A:[こたばくはつ]/B:[んたせいのか]/C:[せいえい頭れ]/D:[のるたは宝た]/E:[うたがわめい]/F[ここちがう！]",
    hint: "表にしてみたら、AとかBとかわかるはず。こたえはそのまま書いてるよ。ななめに読んでね",
    Answer: "ME",
  },
  {
    id: "1",
    number: "2",
    title: "??に入る2文字は?",
    question: "a□□×e / ▲o▲onu■ / s■▼a※be??★",
    hint: "全部果物の名前で同じ記号には同じ文字が入るよ",
    Answer: "RR",
  },
  {
    id: "2",
    number: "3",
    title: "??に入る2文字は？",
    question: "小=● 中=▲ 大=□ 特大=?? 極大=□□ 最大=XX□",
    hint: "同じ記号には同じ文字。最大のところはバツマークではないよ",
    Answer: "LL",
  },
  {
    id: "3",
    number: "4",
    title: "次の問題の答えは？",
    question: "13番目を180°回すと出てくる文字は？",
    hint: "A=1,B=2,C=3....",
    Answer: "W",
  },
  {
    id: "4",
    number: "5",
    title: "?? に入る2文字は?",
    question: "Li/Y/Nu = SO , AH/OCNM/IIJ = DO , min/rak/BIG = ??",
    hint: "SO=白い犬 DO=黄色いインコ ??=太郎三人衆",
    Answer: "AU",
  },
  {
    id: "5",
    number: "6",
    title: " / の右側に共通することは何？",
    question: "[人間 / 猿][イルカ / クラゲ][スズメ / 七面鳥]",
    hint: "英語にしてみると右にだけ入ってる１文字があるよ",
    Answer: "Y",
  },
  {
    id: "6",
    number: "7",
    title: "□に入るランキングの頭文字は?",
    question: "9=F 8=W 7=L 5=D 2=□",
    hint: "他にはKING とか MOS とかあるランキング。一番よく行ってるはず",
    Answer: "M",
  },
  {
    id: "7",
    number: "8",
    title: "？に入る1文字は？",
    question: "[👀→□●□→?]",
    hint: "音だけで変換していこう",
    Answer: "I",
  },
];
